-- 1st Question: List all unique cities where customers are located
select distinct customer_city from ecommerce.customers;

-- 2nd Question: Count the number of orders placed in 2017
select count(order_id) from orders where year(order_purchase_timestamp) = 2017;

-- 3rd Question: Find the total sales per category
select products.product_category, sum(payments.payment_value) as sales
from ecommerce.products join ecommerce.order_items
on products.product_id = order_items.product_id
join ecommerce.payments
on payments.order_id = order_items.order_id
group by products.product_category;

-- 4th Question: Calculate the percentage of orders that were paid in installments
select count(case when payment_installments >= 1 then 1 end) * 100/ count(order_id) as installments_percentage
from ecommerce.payments;

-- 5th Question: Count the number of customers from each state
select customer_state, count(*) as customer_count from ecommerce.customers
group by customer_state;

-- 6th Question: Calculate the number of orders per month in 2018
select monthname(order_purchase_timestamp) as month, count(*) as order_count
from ecommerce.orders
where year(order_purchase_timestamp) = 2018
group by month
order by order_count desc;

-- 7th Question: Find the average number of products per order, grouped by customer city
with products_per_order as (
select orders.order_id, orders.customer_id, count(order_items.order_item_id) as abc
from ecommerce.orders join ecommerce.order_items
on orders.order_id = order_items.order_id
group by orders.order_id, orders.customer_id
)
select customers.customer_city, round(avg(abc), 2) as average
from ecommerce.customers join products_per_order
on customers.customer_id = products_per_order.customer_id
group by customers.customer_city
order by average desc;

-- 8th Question: Calculate the percentage of total revenue contributed by each product category
select products.product_category, round(sum(payments.payment_value)* 100/ (select sum(payment_value) from ecommerce.payments), 2) as revenue_percentage
from ecommerce.products join ecommerce.order_items
on products.product_id = order_items.product_id
join ecommerce.payments
on payments.order_id = order_items.order_id
group by products.product_category;

-- 9th Question: Identify the correlation between product price and the number of times a product has been purchased
select products.product_category, count(order_items.order_item_id) as order_count, round(sum(payments.payment_value), 2) as product_price
from ecommerce.products join ecommerce.order_items
on products.product_id = order_items.product_id
join ecommerce.payments
on payments.order_id = order_items.order_id
group by products.product_category;

-- 10th Question: Calculate the total revenue generated by each seller, and rank them by revenue
select *, dense_rank() over (order by revenue desc) as rnk
from (
select order_items.seller_id, round(sum(payments.payment_value), 2) as revenue
from ecommerce.payments join ecommerce.order_items
on payments.order_id = order_items.order_id
group by order_items.seller_id
) t;

-- 11th Question: Calculate the moving average of order values for each customer over their order history
select customer_id, order_purchase_timestamp, payment,
round(avg(payment) over (partition by customer_id order by order_purchase_timestamp rows between 2 preceding and current row), 2) as moving_average
from (
select orders.customer_id, orders.order_purchase_timestamp, payments.payment_value as payment
from ecommerce.payments join ecommerce.orders
on payments.order_id = orders.order_id
) as r;

-- 12th Question: Calculate the cumulative sales per month for each year
select year(orders.order_purchase_timestamp) as year, month(orders.order_purchase_timestamp) as month, round(sum(payments.payment_value), 2) as sales
from ecommerce.orders join ecommerce.payments
on orders.order_id = payments.order_id
group by year, month
order by year, month;

-- 13th Question: Calculate the year-over-year growth rate of total sales
with a as (
select year(orders.order_purchase_timestamp) as year, round(sum(payments.payment_value), 2) as sales
from ecommerce.orders join ecommerce.payments
on orders.order_id = payments.order_id
group by year
order by year
), 
b as (
select year, sales, lag(sales) over (order by year) as last_year_sales from a
)
select year, round((sales - last_year_sales) * 100 / last_year_sales, 2) as yoy_growth from b;


-- 14th Question: Calculate the retention rate of customers, defined as the percentage of customers who make another purchase within 6 months of their first purchase
with a as (select customers.customer_id,
min(orders.order_purchase_timestamp) first_order
from ecommerce.customers join ecommerce.orders
on customers.customer_id = orders.customer_id
group by customers.customer_id),

b as (select a.customer_id, count(distinct orders.order_purchase_timestamp) next_order
from a join ecommerce.orders
on orders.customer_id = a.customer_id
and orders.order_purchase_timestamp > first_order
and orders.order_purchase_timestamp < 
date_add(first_order, interval 6 month)
group by a.customer_id) 

select 100 * (count( distinct a.customer_id)/ count(distinct b.customer_id)) as retention_rate
from a left join b 
on a.customer_id = b.customer_id ;

-- 15th Question: Identify the top 3 customers who spent the most money in each year
select years, customer_id, payment, d_rank
from
(select year(orders.order_purchase_timestamp) years,
orders.customer_id,
sum(payments.payment_value) payment,
dense_rank() over(partition by year(orders.order_purchase_timestamp)
order by sum(payments.payment_value) desc) d_rank
from ecommerce.orders join ecommerce.payments 
on payments.order_id = orders.order_id
group by year(orders.order_purchase_timestamp),
orders.customer_id) as a
where d_rank <= 3 ;
